time:
  dt_minutes: 5
  horizon_hours: 168
network:
  n_stations: 20
  capacity_default: 12
  distance_km:
  - - 0.0
    - 4.1
    - 6.69
    - 6.39
    - 2.5
    - 5.28
    - 5.62
    - 8.55
    - 7.96
    - 7.81
    - 7.3
    - 5.86
    - 7.5
    - 3.12
    - 10.83
    - 8.72
    - 2.72
    - 7.74
    - 9.9
    - 10.9
  - - 4.1
    - 0.0
    - 10.59
    - 3.15
    - 2.45
    - 9.36
    - 9.18
    - 8.33
    - 11.99
    - 9.13
    - 6.9
    - 4.91
    - 9.61
    - 6.27
    - 7.98
    - 6.07
    - 6.63
    - 11.41
    - 11.19
    - 7.46
  - - 6.69
    - 10.59
    - 0.0
    - 11.98
    - 9.16
    - 3.36
    - 2.01
    - 13.83
    - 1.81
    - 11.74
    - 9.83
    - 9.73
    - 10.44
    - 7.03
    - 17.39
    - 13.29
    - 5.38
    - 6.77
    - 13.35
    - 17.58
  - - 6.39
    - 3.15
    - 11.98
    - 0.0
    - 5.5
    - 11.53
    - 10.24
    - 11.31
    - 13.61
    - 12.29
    - 5.15
    - 3.34
    - 12.73
    - 9.11
    - 9.65
    - 2.96
    - 9.11
    - 14.1
    - 14.33
    - 8.48
  - - 2.5
    - 2.45
    - 9.16
    - 5.5
    - 0.0
    - 7.36
    - 8.12
    - 6.8
    - 10.33
    - 6.96
    - 8.19
    - 6.36
    - 7.24
    - 3.86
    - 8.34
    - 8.31
    - 4.49
    - 9.04
    - 9.06
    - 8.42
  - - 5.28
    - 9.36
    - 3.36
    - 11.53
    - 7.36
    - 0.0
    - 4.24
    - 10.81
    - 3.47
    - 8.48
    - 10.88
    - 10.15
    - 7.1
    - 4.23
    - 15.06
    - 13.5
    - 2.9
    - 3.76
    - 10.01
    - 15.58
  - - 5.62
    - 9.18
    - 2.01
    - 10.24
    - 8.12
    - 4.24
    - 0.0
    - 13.58
    - 3.82
    - 11.89
    - 7.82
    - 7.8
    - 10.83
    - 6.84
    - 16.45
    - 11.37
    - 5.17
    - 7.97
    - 13.7
    - 16.44
  - - 8.55
    - 8.33
    - 13.83
    - 11.31
    - 6.8
    - 10.81
    - 13.58
    - 0.0
    - 14.29
    - 3.22
    - 14.94
    - 13.05
    - 4.98
    - 6.81
    - 6.28
    - 14.27
    - 8.49
    - 9.89
    - 4.11
    - 7.96
  - - 7.96
    - 11.99
    - 1.81
    - 13.61
    - 10.33
    - 3.47
    - 3.82
    - 14.29
    - 0.0
    - 11.88
    - 11.64
    - 11.5
    - 10.39
    - 7.64
    - 18.36
    - 15.05
    - 6.14
    - 6.03
    - 13.27
    - 18.73
  - - 7.81
    - 9.13
    - 11.74
    - 12.29
    - 6.96
    - 8.48
    - 11.89
    - 3.22
    - 11.88
    - 0.0
    - 14.95
    - 13.24
    - 1.8
    - 5.15
    - 9.35
    - 15.19
    - 6.75
    - 6.88
    - 2.12
    - 10.83
  - - 7.3
    - 6.9
    - 9.83
    - 5.15
    - 8.19
    - 10.88
    - 7.82
    - 14.94
    - 11.64
    - 14.95
    - 0.0
    - 2.0
    - 14.79
    - 10.4
    - 14.59
    - 4.31
    - 9.53
    - 14.32
    - 17.06
    - 13.59
  - - 5.86
    - 4.91
    - 9.73
    - 3.34
    - 6.36
    - 10.15
    - 7.8
    - 13.05
    - 11.5
    - 13.24
    - 2.0
    - 0.0
    - 13.24
    - 8.98
    - 12.61
    - 3.57
    - 8.36
    - 13.34
    - 15.36
    - 11.66
  - - 7.5
    - 9.61
    - 10.44
    - 12.73
    - 7.24
    - 7.1
    - 10.83
    - 4.98
    - 10.39
    - 1.8
    - 14.79
    - 13.24
    - 0.0
    - 4.48
    - 10.96
    - 15.54
    - 5.86
    - 5.12
    - 2.91
    - 12.31
  - - 3.12
    - 6.27
    - 7.03
    - 9.11
    - 3.86
    - 4.23
    - 6.84
    - 6.81
    - 7.64
    - 5.15
    - 10.4
    - 8.98
    - 4.48
    - 0.0
    - 10.87
    - 11.67
    - 1.68
    - 5.18
    - 7.12
    - 11.51
  - - 10.83
    - 7.98
    - 17.39
    - 9.65
    - 8.34
    - 15.06
    - 16.45
    - 6.28
    - 18.36
    - 9.35
    - 14.59
    - 12.61
    - 10.96
    - 10.87
    - 0.0
    - 12.15
    - 12.23
    - 15.32
    - 10.36
    - 2.08
  - - 8.72
    - 6.07
    - 13.29
    - 2.96
    - 8.31
    - 13.5
    - 11.37
    - 14.27
    - 15.05
    - 15.19
    - 4.31
    - 3.57
    - 15.54
    - 11.67
    - 12.15
    - 0.0
    - 11.4
    - 16.44
    - 17.25
    - 10.7
  - - 2.72
    - 6.63
    - 5.38
    - 9.11
    - 4.49
    - 2.9
    - 5.17
    - 8.49
    - 6.14
    - 6.75
    - 9.53
    - 8.36
    - 5.86
    - 1.68
    - 12.23
    - 11.4
    - 0.0
    - 5.04
    - 8.64
    - 12.69
  - - 7.74
    - 11.41
    - 6.77
    - 14.1
    - 9.04
    - 3.76
    - 7.97
    - 9.89
    - 6.03
    - 6.88
    - 14.32
    - 13.34
    - 5.12
    - 5.18
    - 15.32
    - 16.44
    - 5.04
    - 0.0
    - 7.73
    - 16.3
  - - 9.9
    - 11.19
    - 13.35
    - 14.33
    - 9.06
    - 10.01
    - 13.7
    - 4.11
    - 13.27
    - 2.12
    - 17.06
    - 15.36
    - 2.91
    - 7.12
    - 10.36
    - 17.25
    - 8.64
    - 7.73
    - 0.0
    - 12.07
  - - 10.9
    - 7.46
    - 17.58
    - 8.48
    - 8.42
    - 15.58
    - 16.44
    - 7.96
    - 18.73
    - 10.83
    - 13.59
    - 11.66
    - 12.31
    - 11.51
    - 2.08
    - 10.7
    - 12.69
    - 16.3
    - 12.07
    - 0.0
  travel_time_min:
  - - 0.0
    - 16.4
    - 26.8
    - 25.6
    - 10.0
    - 21.1
    - 22.5
    - 34.2
    - 31.8
    - 31.3
    - 29.2
    - 23.5
    - 30.0
    - 12.5
    - 43.3
    - 34.9
    - 10.9
    - 31.0
    - 39.6
    - 43.6
  - - 16.4
    - 0.0
    - 42.3
    - 12.6
    - 9.8
    - 37.4
    - 36.7
    - 33.3
    - 48.0
    - 36.5
    - 27.6
    - 19.6
    - 38.4
    - 25.1
    - 31.9
    - 24.3
    - 26.5
    - 45.7
    - 44.7
    - 29.9
  - - 26.8
    - 42.3
    - 0.0
    - 47.9
    - 36.6
    - 13.4
    - 8.0
    - 55.3
    - 7.2
    - 47.0
    - 39.3
    - 38.9
    - 41.7
    - 28.1
    - 69.5
    - 53.2
    - 21.5
    - 27.1
    - 53.4
    - 70.3
  - - 25.6
    - 12.6
    - 47.9
    - 0.0
    - 22.0
    - 46.1
    - 41.0
    - 45.3
    - 54.5
    - 49.1
    - 20.6
    - 13.4
    - 50.9
    - 36.4
    - 38.6
    - 11.8
    - 36.4
    - 56.4
    - 57.3
    - 33.9
  - - 10.0
    - 9.8
    - 36.6
    - 22.0
    - 0.0
    - 29.4
    - 32.5
    - 27.2
    - 41.3
    - 27.8
    - 32.7
    - 25.4
    - 29.0
    - 15.5
    - 33.3
    - 33.2
    - 18.0
    - 36.2
    - 36.3
    - 33.7
  - - 21.1
    - 37.4
    - 13.4
    - 46.1
    - 29.4
    - 0.0
    - 17.0
    - 43.3
    - 13.9
    - 33.9
    - 43.5
    - 40.6
    - 28.4
    - 16.9
    - 60.2
    - 54.0
    - 11.6
    - 15.0
    - 40.0
    - 62.3
  - - 22.5
    - 36.7
    - 8.0
    - 41.0
    - 32.5
    - 17.0
    - 0.0
    - 54.3
    - 15.3
    - 47.6
    - 31.3
    - 31.2
    - 43.3
    - 27.4
    - 65.8
    - 45.5
    - 20.7
    - 31.9
    - 54.8
    - 65.8
  - - 34.2
    - 33.3
    - 55.3
    - 45.3
    - 27.2
    - 43.3
    - 54.3
    - 0.0
    - 57.1
    - 12.9
    - 59.8
    - 52.2
    - 19.9
    - 27.3
    - 25.1
    - 57.1
    - 34.0
    - 39.6
    - 16.5
    - 31.8
  - - 31.8
    - 48.0
    - 7.2
    - 54.5
    - 41.3
    - 13.9
    - 15.3
    - 57.1
    - 0.0
    - 47.5
    - 46.5
    - 46.0
    - 41.6
    - 30.6
    - 73.5
    - 60.2
    - 24.6
    - 24.1
    - 53.1
    - 74.9
  - - 31.3
    - 36.5
    - 47.0
    - 49.1
    - 27.8
    - 33.9
    - 47.6
    - 12.9
    - 47.5
    - 0.0
    - 59.8
    - 53.0
    - 7.2
    - 20.6
    - 37.4
    - 60.8
    - 27.0
    - 27.5
    - 8.5
    - 43.3
  - - 29.2
    - 27.6
    - 39.3
    - 20.6
    - 32.7
    - 43.5
    - 31.3
    - 59.8
    - 46.5
    - 59.8
    - 0.0
    - 8.0
    - 59.2
    - 41.6
    - 58.4
    - 17.2
    - 38.1
    - 57.3
    - 68.2
    - 54.4
  - - 23.5
    - 19.6
    - 38.9
    - 13.4
    - 25.4
    - 40.6
    - 31.2
    - 52.2
    - 46.0
    - 53.0
    - 8.0
    - 0.0
    - 52.9
    - 35.9
    - 50.4
    - 14.3
    - 33.4
    - 53.3
    - 61.4
    - 46.7
  - - 30.0
    - 38.4
    - 41.7
    - 50.9
    - 29.0
    - 28.4
    - 43.3
    - 19.9
    - 41.6
    - 7.2
    - 59.2
    - 52.9
    - 0.0
    - 17.9
    - 43.8
    - 62.2
    - 23.4
    - 20.5
    - 11.7
    - 49.3
  - - 12.5
    - 25.1
    - 28.1
    - 36.4
    - 15.5
    - 16.9
    - 27.4
    - 27.3
    - 30.6
    - 20.6
    - 41.6
    - 35.9
    - 17.9
    - 0.0
    - 43.5
    - 46.7
    - 6.7
    - 20.7
    - 28.5
    - 46.0
  - - 43.3
    - 31.9
    - 69.5
    - 38.6
    - 33.3
    - 60.2
    - 65.8
    - 25.1
    - 73.5
    - 37.4
    - 58.4
    - 50.4
    - 43.8
    - 43.5
    - 0.0
    - 48.6
    - 48.9
    - 61.3
    - 41.5
    - 8.3
  - - 34.9
    - 24.3
    - 53.2
    - 11.8
    - 33.2
    - 54.0
    - 45.5
    - 57.1
    - 60.2
    - 60.8
    - 17.2
    - 14.3
    - 62.2
    - 46.7
    - 48.6
    - 0.0
    - 45.6
    - 65.8
    - 69.0
    - 42.8
  - - 10.9
    - 26.5
    - 21.5
    - 36.4
    - 18.0
    - 11.6
    - 20.7
    - 34.0
    - 24.6
    - 27.0
    - 38.1
    - 33.4
    - 23.4
    - 6.7
    - 48.9
    - 45.6
    - 0.0
    - 20.2
    - 34.5
    - 50.7
  - - 31.0
    - 45.7
    - 27.1
    - 56.4
    - 36.2
    - 15.0
    - 31.9
    - 39.6
    - 24.1
    - 27.5
    - 57.3
    - 53.3
    - 20.5
    - 20.7
    - 61.3
    - 65.8
    - 20.2
    - 0.0
    - 30.9
    - 65.2
  - - 39.6
    - 44.7
    - 53.4
    - 57.3
    - 36.3
    - 40.0
    - 54.8
    - 16.5
    - 53.1
    - 8.5
    - 68.2
    - 61.4
    - 11.7
    - 28.5
    - 41.5
    - 69.0
    - 34.5
    - 30.9
    - 0.0
    - 48.3
  - - 43.6
    - 29.9
    - 70.3
    - 33.9
    - 33.7
    - 62.3
    - 65.8
    - 31.8
    - 74.9
    - 43.3
    - 54.4
    - 46.7
    - 49.3
    - 46.0
    - 8.3
    - 42.8
    - 50.7
    - 65.2
    - 48.3
    - 0.0
  station_ids:
  - S1
  - S2
  - S3
  - S4
  - S5
  - S6
  - S7
  - S8
  - S9
  - S10
  - S11
  - S12
  - S13
  - S14
  - S15
  - S16
  - S17
  - S18
  - S19
  - S20
  station_names:
  - Station_1
  - Station_2
  - Station_3
  - Station_4
  - Station_5
  - Station_6
  - Station_7
  - Station_8
  - Station_9
  - Station_10
  - Station_11
  - Station_12
  - Station_13
  - Station_14
  - Station_15
  - Station_16
  - Station_17
  - Station_18
  - Station_19
  - Station_20
  lat:
  - 41.1561363
  - 41.1287639
  - 41.1816843
  - 41.1013555
  - 41.150639
  - 41.1949498
  - 41.1642254
  - 41.188551
  - 41.1974869
  - 41.2075357
  - 41.0971448
  - 41.1048914
  - 41.2147178
  - 41.1828204
  - 41.1383995
  - 41.0778976
  - 41.1798232
  - 41.2248185
  - 41.2236455
  - 41.1202525
  lon:
  - -8.6521673
  - -8.6194107
  - -8.7245208
  - -8.6291255
  - -8.6231736
  - -8.6884533
  - -8.718453
  - -8.5594878
  - -8.7298121
  - -8.5884808
  - -8.6903159
  - -8.6687462
  - -8.6077721
  - -8.6405687
  - -8.5249621
  - -8.6457219
  - -8.6602497
  - -8.6674938
  - -8.5750279
  - -8.531019
demand:
  base_lambda_per_dt: 0.35
energy:
  chargers_per_station:
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  charge_rate_soc_per_hour:
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  battery_kwh_per_vehicle: 0.5
  energy_cost_per_kwh_eur: 0.2
score:
  objective: client_satisfaction_normalized
  weights:
    w_unavail: 5.0
    w_reloc: 1.0
    w_charge: 1.0
    w_queue: 4.0
    scales:
    U0_unavailability: 0.745528
    R0_reloc_km: 0.816189
    C0_charge_cost_eur: 0.027335
    Q0_queue_total: 234.699074
  eps: 1.0e-06
seed: 42
meta:
  city: Porto, Portugal (synthetic)
  generator: synthetic_min_spacing
  center_lat: 41.162
  center_lon: -8.63
  radius_km: 10.0
  min_spacing_m: 900.0
  speed_kmh_for_travel_time: 15.0
