time:
  dt_minutes: 5
  horizon_hours: 168
network:
  n_stations: 20
  capacity_default: 12
  distance_km:
  - - 0.0
    - 6.44
    - 11.81
    - 2.93
    - 1.22
    - 10.14
    - 5.92
    - 12.84
    - 9.98
    - 1.13
    - 11.65
    - 4.69
    - 11.85
    - 4.34
    - 13.37
    - 10.9
    - 2.06
    - 11.3
    - 13.12
    - 13.66
  - - 6.44
    - 0.0
    - 10.97
    - 5.77
    - 5.43
    - 6.17
    - 2.92
    - 9.12
    - 7.27
    - 7.55
    - 11.37
    - 1.93
    - 5.41
    - 3.04
    - 10.84
    - 11.4
    - 7.22
    - 7.85
    - 10.93
    - 10.54
  - - 11.81
    - 10.97
    - 0.0
    - 13.88
    - 10.84
    - 6.08
    - 8.17
    - 5.38
    - 4.16
    - 12.12
    - 1.0
    - 11.53
    - 12.91
    - 9.09
    - 3.28
    - 2.36
    - 10.24
    - 4.86
    - 2.61
    - 4.43
  - - 2.93
    - 5.77
    - 13.88
    - 0.0
    - 3.26
    - 10.99
    - 6.63
    - 13.91
    - 11.33
    - 3.71
    - 13.87
    - 3.85
    - 10.89
    - 5.14
    - 14.93
    - 13.31
    - 4.96
    - 12.43
    - 14.79
    - 15.0
  - - 1.22
    - 5.43
    - 10.84
    - 3.26
    - 0.0
    - 8.93
    - 4.71
    - 11.65
    - 8.82
    - 2.2
    - 10.75
    - 3.83
    - 10.82
    - 3.14
    - 12.26
    - 10.1
    - 2.07
    - 10.11
    - 12.04
    - 12.51
  - - 10.14
    - 6.17
    - 6.08
    - 10.99
    - 8.93
    - 0.0
    - 4.38
    - 2.98
    - 1.96
    - 10.96
    - 6.85
    - 7.51
    - 6.85
    - 5.95
    - 4.84
    - 7.57
    - 9.57
    - 1.73
    - 5.09
    - 4.39
  - - 5.92
    - 2.92
    - 8.17
    - 6.63
    - 4.71
    - 4.38
    - 0.0
    - 7.28
    - 4.84
    - 6.86
    - 8.5
    - 3.43
    - 7.07
    - 1.6
    - 8.49
    - 8.48
    - 5.81
    - 5.81
    - 8.47
    - 8.43
  - - 12.84
    - 9.12
    - 5.38
    - 13.91
    - 11.65
    - 2.98
    - 7.28
    - 0.0
    - 3.03
    - 13.57
    - 6.36
    - 10.49
    - 8.78
    - 8.81
    - 2.7
    - 7.52
    - 12.02
    - 1.55
    - 3.26
    - 1.72
  - - 9.98
    - 7.27
    - 4.16
    - 11.33
    - 8.82
    - 1.96
    - 4.84
    - 3.03
    - 0.0
    - 10.64
    - 4.9
    - 8.26
    - 8.76
    - 6.2
    - 3.65
    - 5.62
    - 9.03
    - 1.54
    - 3.67
    - 3.7
  - - 1.13
    - 7.55
    - 12.12
    - 3.71
    - 2.2
    - 10.96
    - 6.86
    - 13.57
    - 10.64
    - 0.0
    - 11.87
    - 5.82
    - 12.96
    - 5.32
    - 13.91
    - 11.01
    - 1.91
    - 12.02
    - 13.62
    - 14.29
  - - 11.65
    - 11.37
    - 1.0
    - 13.87
    - 10.75
    - 6.85
    - 8.5
    - 6.36
    - 4.9
    - 11.87
    - 0.0
    - 11.77
    - 13.64
    - 9.27
    - 4.26
    - 1.43
    - 9.97
    - 5.74
    - 3.59
    - 5.43
  - - 4.69
    - 1.93
    - 11.53
    - 3.85
    - 3.83
    - 7.51
    - 3.43
    - 10.49
    - 8.26
    - 5.82
    - 11.77
    - 0.0
    - 7.25
    - 2.55
    - 11.9
    - 11.57
    - 5.8
    - 9.1
    - 11.9
    - 11.77
  - - 11.85
    - 5.41
    - 12.91
    - 10.89
    - 10.82
    - 6.85
    - 7.07
    - 8.78
    - 8.76
    - 12.96
    - 13.64
    - 7.25
    - 0.0
    - 8.06
    - 11.34
    - 14.21
    - 12.49
    - 8.32
    - 11.74
    - 10.5
  - - 4.34
    - 3.04
    - 9.09
    - 5.14
    - 3.14
    - 5.95
    - 1.6
    - 8.81
    - 6.2
    - 5.32
    - 9.27
    - 2.55
    - 8.06
    - 0.0
    - 9.82
    - 9.02
    - 4.47
    - 7.31
    - 9.72
    - 9.87
  - - 13.37
    - 10.84
    - 3.28
    - 14.93
    - 12.26
    - 4.84
    - 8.49
    - 2.7
    - 3.65
    - 13.91
    - 4.26
    - 11.9
    - 11.34
    - 9.82
    - 0.0
    - 5.62
    - 12.16
    - 3.13
    - 0.69
    - 1.23
  - - 10.9
    - 11.4
    - 2.36
    - 13.31
    - 10.1
    - 7.57
    - 8.48
    - 7.52
    - 5.62
    - 11.01
    - 1.43
    - 11.57
    - 14.21
    - 9.02
    - 5.62
    - 0.0
    - 9.1
    - 6.71
    - 4.96
    - 6.75
  - - 2.06
    - 7.22
    - 10.24
    - 4.96
    - 2.07
    - 9.57
    - 5.81
    - 12.02
    - 9.03
    - 1.91
    - 9.97
    - 5.8
    - 12.49
    - 4.47
    - 12.16
    - 9.1
    - 0.0
    - 10.47
    - 11.83
    - 12.61
  - - 11.3
    - 7.85
    - 4.86
    - 12.43
    - 10.11
    - 1.73
    - 5.81
    - 1.55
    - 1.54
    - 12.02
    - 5.74
    - 9.1
    - 8.32
    - 7.31
    - 3.13
    - 6.71
    - 10.47
    - 0.0
    - 3.44
    - 2.69
  - - 13.12
    - 10.93
    - 2.61
    - 14.79
    - 12.04
    - 5.09
    - 8.47
    - 3.26
    - 3.67
    - 13.62
    - 3.59
    - 11.9
    - 11.74
    - 9.72
    - 0.69
    - 4.96
    - 11.83
    - 3.44
    - 0.0
    - 1.91
  - - 13.66
    - 10.54
    - 4.43
    - 15.0
    - 12.51
    - 4.39
    - 8.43
    - 1.72
    - 3.7
    - 14.29
    - 5.43
    - 11.77
    - 10.5
    - 9.87
    - 1.23
    - 6.75
    - 12.61
    - 2.69
    - 1.91
    - 0.0
  travel_time_min:
  - - 0.0
    - 25.8
    - 47.2
    - 11.7
    - 4.9
    - 40.6
    - 23.7
    - 51.4
    - 39.9
    - 4.5
    - 46.6
    - 18.8
    - 47.4
    - 17.4
    - 53.5
    - 43.6
    - 8.2
    - 45.2
    - 52.5
    - 54.6
  - - 25.8
    - 0.0
    - 43.9
    - 23.1
    - 21.7
    - 24.7
    - 11.7
    - 36.5
    - 29.1
    - 30.2
    - 45.5
    - 7.7
    - 21.6
    - 12.2
    - 43.4
    - 45.6
    - 28.9
    - 31.4
    - 43.7
    - 42.2
  - - 47.2
    - 43.9
    - 0.0
    - 55.5
    - 43.4
    - 24.3
    - 32.7
    - 21.5
    - 16.7
    - 48.5
    - 4.0
    - 46.1
    - 51.7
    - 36.4
    - 13.1
    - 9.4
    - 41.0
    - 19.4
    - 10.4
    - 17.7
  - - 11.7
    - 23.1
    - 55.5
    - 0.0
    - 13.0
    - 44.0
    - 26.5
    - 55.6
    - 45.3
    - 14.8
    - 55.5
    - 15.4
    - 43.5
    - 20.5
    - 59.7
    - 53.2
    - 19.8
    - 49.7
    - 59.2
    - 60.0
  - - 4.9
    - 21.7
    - 43.4
    - 13.0
    - 0.0
    - 35.7
    - 18.8
    - 46.6
    - 35.3
    - 8.8
    - 43.0
    - 15.3
    - 43.3
    - 12.6
    - 49.0
    - 40.4
    - 8.3
    - 40.4
    - 48.1
    - 50.0
  - - 40.6
    - 24.7
    - 24.3
    - 44.0
    - 35.7
    - 0.0
    - 17.5
    - 11.9
    - 7.8
    - 43.8
    - 27.4
    - 30.1
    - 27.4
    - 23.8
    - 19.4
    - 30.3
    - 38.3
    - 6.9
    - 20.4
    - 17.6
  - - 23.7
    - 11.7
    - 32.7
    - 26.5
    - 18.8
    - 17.5
    - 0.0
    - 29.1
    - 19.4
    - 27.4
    - 34.0
    - 13.7
    - 28.3
    - 6.4
    - 34.0
    - 33.9
    - 23.3
    - 23.3
    - 33.9
    - 33.7
  - - 51.4
    - 36.5
    - 21.5
    - 55.6
    - 46.6
    - 11.9
    - 29.1
    - 0.0
    - 12.1
    - 54.3
    - 25.4
    - 42.0
    - 35.1
    - 35.2
    - 10.8
    - 30.1
    - 48.1
    - 6.2
    - 13.0
    - 6.9
  - - 39.9
    - 29.1
    - 16.7
    - 45.3
    - 35.3
    - 7.8
    - 19.4
    - 12.1
    - 0.0
    - 42.6
    - 19.6
    - 33.0
    - 35.0
    - 24.8
    - 14.6
    - 22.5
    - 36.1
    - 6.2
    - 14.7
    - 14.8
  - - 4.5
    - 30.2
    - 48.5
    - 14.8
    - 8.8
    - 43.8
    - 27.4
    - 54.3
    - 42.6
    - 0.0
    - 47.5
    - 23.3
    - 51.8
    - 21.3
    - 55.7
    - 44.0
    - 7.6
    - 48.1
    - 54.5
    - 57.2
  - - 46.6
    - 45.5
    - 4.0
    - 55.5
    - 43.0
    - 27.4
    - 34.0
    - 25.4
    - 19.6
    - 47.5
    - 0.0
    - 47.1
    - 54.6
    - 37.1
    - 17.1
    - 5.7
    - 39.9
    - 23.0
    - 14.4
    - 21.7
  - - 18.8
    - 7.7
    - 46.1
    - 15.4
    - 15.3
    - 30.1
    - 13.7
    - 42.0
    - 33.0
    - 23.3
    - 47.1
    - 0.0
    - 29.0
    - 10.2
    - 47.6
    - 46.3
    - 23.2
    - 36.4
    - 47.6
    - 47.1
  - - 47.4
    - 21.6
    - 51.7
    - 43.5
    - 43.3
    - 27.4
    - 28.3
    - 35.1
    - 35.0
    - 51.8
    - 54.6
    - 29.0
    - 0.0
    - 32.3
    - 45.3
    - 56.8
    - 50.0
    - 33.3
    - 46.9
    - 42.0
  - - 17.4
    - 12.2
    - 36.4
    - 20.5
    - 12.6
    - 23.8
    - 6.4
    - 35.2
    - 24.8
    - 21.3
    - 37.1
    - 10.2
    - 32.3
    - 0.0
    - 39.3
    - 36.1
    - 17.9
    - 29.2
    - 38.9
    - 39.5
  - - 53.5
    - 43.4
    - 13.1
    - 59.7
    - 49.0
    - 19.4
    - 34.0
    - 10.8
    - 14.6
    - 55.7
    - 17.1
    - 47.6
    - 45.3
    - 39.3
    - 0.0
    - 22.5
    - 48.6
    - 12.5
    - 2.7
    - 4.9
  - - 43.6
    - 45.6
    - 9.4
    - 53.2
    - 40.4
    - 30.3
    - 33.9
    - 30.1
    - 22.5
    - 44.0
    - 5.7
    - 46.3
    - 56.8
    - 36.1
    - 22.5
    - 0.0
    - 36.4
    - 26.8
    - 19.9
    - 27.0
  - - 8.2
    - 28.9
    - 41.0
    - 19.8
    - 8.3
    - 38.3
    - 23.3
    - 48.1
    - 36.1
    - 7.6
    - 39.9
    - 23.2
    - 50.0
    - 17.9
    - 48.6
    - 36.4
    - 0.0
    - 41.9
    - 47.3
    - 50.4
  - - 45.2
    - 31.4
    - 19.4
    - 49.7
    - 40.4
    - 6.9
    - 23.3
    - 6.2
    - 6.2
    - 48.1
    - 23.0
    - 36.4
    - 33.3
    - 29.2
    - 12.5
    - 26.8
    - 41.9
    - 0.0
    - 13.7
    - 10.8
  - - 52.5
    - 43.7
    - 10.4
    - 59.2
    - 48.1
    - 20.4
    - 33.9
    - 13.0
    - 14.7
    - 54.5
    - 14.4
    - 47.6
    - 46.9
    - 38.9
    - 2.7
    - 19.9
    - 47.3
    - 13.7
    - 0.0
    - 7.6
  - - 54.6
    - 42.2
    - 17.7
    - 60.0
    - 50.0
    - 17.6
    - 33.7
    - 6.9
    - 14.8
    - 57.2
    - 21.7
    - 47.1
    - 42.0
    - 39.5
    - 4.9
    - 27.0
    - 50.4
    - 10.8
    - 7.6
    - 0.0
  station_ids:
  - S1
  - S2
  - S3
  - S4
  - S5
  - S6
  - S7
  - S8
  - S9
  - S10
  - S11
  - S12
  - S13
  - S14
  - S15
  - S16
  - S17
  - S18
  - S19
  - S20
  station_names:
  - Station_1
  - Station_2
  - Station_3
  - Station_4
  - Station_5
  - Station_6
  - Station_7
  - Station_8
  - Station_9
  - Station_10
  - Station_11
  - Station_12
  - Station_13
  - Station_14
  - Station_15
  - Station_16
  - Station_17
  - Station_18
  - Station_19
  - Station_20
  lat:
  - 41.2189217
  - 41.1683321
  - 41.1345104
  - 41.2201693
  - 41.2079967
  - 41.1283191
  - 41.1657094
  - 41.1061998
  - 41.1333457
  - 41.226788
  - 41.1412895
  - 41.1855253
  - 41.1254995
  - 41.1800195
  - 41.10925
  - 41.1537765
  - 41.2140255
  - 41.120007
  - 41.1137367
  - 41.1028442
  lon:
  - -8.6180196
  - -8.5805045
  - -8.703595
  - -8.5830257
  - -8.6184258
  - -8.6315059
  - -8.6152042
  - -8.6515038
  - -8.6539086
  - -8.6264841
  - -8.7114142
  - -8.5837202
  - -8.5498632
  - -8.6133537
  - -8.6834566
  - -8.7153096
  - -8.6417854
  - -8.6489176
  - -8.6890884
  - -8.6715102
demand:
  base_lambda_per_dt: 0.35
energy:
  chargers_per_station:
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  charge_rate_soc_per_hour:
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  battery_kwh_per_vehicle: 0.5
  energy_cost_per_kwh_eur: 0.2
score:
  objective: client_satisfaction_normalized
  weights:
    w_unavail: 5.0
    w_reloc: 1.0
    w_charge: 1.0
    w_queue: 4.0
  scales:
    U0_unavailability: 0.719886
    R0_reloc_km: 0.964876
    C0_charge_cost_eur: 0.027856
    Q0_queue_total: 205.706597
  eps: 1.0e-06
seed: 42
meta:
  city: Porto, Portugal (synthetic)
  generator: synthetic_min_spacing
  center_lat: 41.162
  center_lon: -8.63
  radius_km: 8.0
  min_spacing_m: 600.0
  speed_kmh_for_travel_time: 15.0
