time:
  dt_minutes: 5
  horizon_hours: 168
network:
  n_stations: 20
  capacity_default: 12
  distance_km:
  - - 0.0
    - 12.93
    - 10.03
    - 8.8
    - 2.34
    - 7.33
    - 4.72
    - 8.43
    - 6.92
    - 12.54
    - 8.06
    - 14.29
    - 12.56
    - 5.02
    - 11.08
    - 7.62
    - 10.06
    - 11.72
    - 7.85
    - 4.51
  - - 12.93
    - 0.0
    - 6.73
    - 7.35
    - 10.67
    - 17.31
    - 9.39
    - 7.22
    - 9.84
    - 3.36
    - 6.4
    - 3.72
    - 9.43
    - 8.11
    - 10.73
    - 5.32
    - 14.27
    - 6.43
    - 15.7
    - 16.41
  - - 10.03
    - 6.73
    - 0.0
    - 1.28
    - 7.84
    - 11.75
    - 9.1
    - 9.65
    - 4.03
    - 3.99
    - 2.3
    - 5.45
    - 3.51
    - 5.49
    - 4.06
    - 5.41
    - 7.63
    - 1.7
    - 9.66
    - 11.93
  - - 8.8
    - 7.35
    - 1.28
    - 0.0
    - 6.65
    - 10.58
    - 8.21
    - 9.2
    - 2.82
    - 4.99
    - 1.6
    - 6.57
    - 4.21
    - 4.45
    - 4.02
    - 4.97
    - 6.93
    - 2.98
    - 8.59
    - 10.65
  - - 2.34
    - 10.67
    - 7.84
    - 6.65
    - 0.0
    - 8.12
    - 3.58
    - 6.97
    - 5.19
    - 10.2
    - 5.77
    - 11.96
    - 10.61
    - 2.69
    - 9.38
    - 5.39
    - 9.21
    - 9.5
    - 7.86
    - 6.06
  - - 7.33
    - 17.31
    - 11.75
    - 10.58
    - 8.12
    - 0.0
    - 11.62
    - 15.07
    - 7.76
    - 15.53
    - 11.0
    - 17.15
    - 12.33
    - 9.7
    - 10.03
    - 12.66
    - 6.35
    - 13.25
    - 2.63
    - 3.46
  - - 4.72
    - 9.39
    - 9.1
    - 8.21
    - 3.58
    - 11.62
    - 0.0
    - 3.72
    - 7.86
    - 10.1
    - 6.8
    - 11.72
    - 12.42
    - 3.88
    - 11.77
    - 4.45
    - 12.46
    - 10.52
    - 11.42
    - 9.19
  - - 8.43
    - 7.22
    - 9.65
    - 9.2
    - 6.97
    - 15.07
    - 3.72
    - 0.0
    - 9.93
    - 9.09
    - 7.6
    - 10.39
    - 13.17
    - 5.96
    - 13.17
    - 4.25
    - 14.89
    - 10.63
    - 14.53
    - 12.85
  - - 6.92
    - 9.84
    - 4.03
    - 2.82
    - 5.19
    - 7.76
    - 7.86
    - 9.93
    - 0.0
    - 7.78
    - 3.45
    - 9.39
    - 5.71
    - 4.09
    - 4.2
    - 6.16
    - 5.0
    - 5.64
    - 5.87
    - 7.98
  - - 12.54
    - 3.36
    - 3.99
    - 4.99
    - 10.2
    - 15.53
    - 10.1
    - 9.09
    - 7.78
    - 0.0
    - 4.72
    - 1.76
    - 6.15
    - 7.52
    - 7.69
    - 5.65
    - 11.59
    - 3.2
    - 13.58
    - 15.27
  - - 8.06
    - 6.4
    - 2.3
    - 1.6
    - 5.77
    - 11.0
    - 6.8
    - 7.6
    - 3.45
    - 4.72
    - 0.0
    - 6.45
    - 5.7
    - 3.26
    - 5.61
    - 3.37
    - 8.16
    - 3.81
    - 9.3
    - 10.56
  - - 14.29
    - 3.72
    - 5.45
    - 6.57
    - 11.96
    - 17.15
    - 11.72
    - 10.39
    - 9.39
    - 1.76
    - 6.45
    - 0.0
    - 6.88
    - 9.27
    - 8.76
    - 7.27
    - 12.88
    - 4.27
    - 15.11
    - 17.0
  - - 12.56
    - 9.43
    - 3.51
    - 4.21
    - 10.61
    - 12.33
    - 12.42
    - 13.17
    - 5.71
    - 6.15
    - 5.7
    - 6.88
    - 0.0
    - 8.63
    - 2.37
    - 8.92
    - 6.71
    - 3.01
    - 9.84
    - 13.43
  - - 5.02
    - 8.11
    - 5.49
    - 4.45
    - 2.69
    - 9.7
    - 3.88
    - 5.96
    - 4.09
    - 7.52
    - 3.26
    - 9.27
    - 8.63
    - 0.0
    - 7.89
    - 3.0
    - 8.96
    - 7.07
    - 8.72
    - 8.33
  - - 11.08
    - 10.73
    - 4.06
    - 4.02
    - 9.38
    - 10.03
    - 11.77
    - 13.17
    - 4.2
    - 7.69
    - 5.61
    - 8.76
    - 2.37
    - 7.89
    - 0.0
    - 8.98
    - 4.36
    - 4.52
    - 7.5
    - 11.38
  - - 7.62
    - 5.32
    - 5.41
    - 4.97
    - 5.39
    - 12.66
    - 4.45
    - 4.25
    - 6.16
    - 5.65
    - 3.37
    - 7.27
    - 8.92
    - 3.0
    - 8.98
    - 0.0
    - 11.14
    - 6.5
    - 11.51
    - 11.3
  - - 10.06
    - 14.27
    - 7.63
    - 6.93
    - 9.21
    - 6.35
    - 12.46
    - 14.89
    - 5.0
    - 11.59
    - 8.16
    - 12.88
    - 6.71
    - 8.96
    - 4.36
    - 11.14
    - 0.0
    - 8.62
    - 3.72
    - 8.65
  - - 11.72
    - 6.43
    - 1.7
    - 2.98
    - 9.5
    - 13.25
    - 10.52
    - 10.63
    - 5.64
    - 3.2
    - 3.81
    - 4.27
    - 3.01
    - 7.07
    - 4.52
    - 6.5
    - 8.62
    - 0.0
    - 11.04
    - 13.59
  - - 7.85
    - 15.7
    - 9.66
    - 8.59
    - 7.86
    - 2.63
    - 11.42
    - 14.53
    - 5.87
    - 13.58
    - 9.3
    - 15.11
    - 9.84
    - 8.72
    - 7.5
    - 11.51
    - 3.72
    - 11.04
    - 0.0
    - 5.23
  - - 4.51
    - 16.41
    - 11.93
    - 10.65
    - 6.06
    - 3.46
    - 9.19
    - 12.85
    - 7.98
    - 15.27
    - 10.56
    - 17.0
    - 13.43
    - 8.33
    - 11.38
    - 11.3
    - 8.65
    - 13.59
    - 5.23
    - 0.0
  travel_time_min:
  - - 0.0
    - 51.7
    - 40.1
    - 35.2
    - 9.3
    - 29.3
    - 18.9
    - 33.7
    - 27.7
    - 50.2
    - 32.2
    - 57.2
    - 50.3
    - 20.1
    - 44.3
    - 30.5
    - 40.2
    - 46.9
    - 31.4
    - 18.0
  - - 51.7
    - 0.0
    - 26.9
    - 29.4
    - 42.7
    - 69.3
    - 37.6
    - 28.9
    - 39.4
    - 13.4
    - 25.6
    - 14.9
    - 37.7
    - 32.4
    - 42.9
    - 21.3
    - 57.1
    - 25.7
    - 62.8
    - 65.7
  - - 40.1
    - 26.9
    - 0.0
    - 5.1
    - 31.4
    - 47.0
    - 36.4
    - 38.6
    - 16.1
    - 15.9
    - 9.2
    - 21.8
    - 14.1
    - 22.0
    - 16.2
    - 21.6
    - 30.5
    - 6.8
    - 38.6
    - 47.7
  - - 35.2
    - 29.4
    - 5.1
    - 0.0
    - 26.6
    - 42.3
    - 32.8
    - 36.8
    - 11.3
    - 19.9
    - 6.4
    - 26.3
    - 16.8
    - 17.8
    - 16.1
    - 19.9
    - 27.7
    - 11.9
    - 34.4
    - 42.6
  - - 9.3
    - 42.7
    - 31.4
    - 26.6
    - 0.0
    - 32.5
    - 14.3
    - 27.9
    - 20.8
    - 40.8
    - 23.1
    - 47.8
    - 42.4
    - 10.7
    - 37.5
    - 21.5
    - 36.8
    - 38.0
    - 31.4
    - 24.2
  - - 29.3
    - 69.3
    - 47.0
    - 42.3
    - 32.5
    - 0.0
    - 46.5
    - 60.3
    - 31.0
    - 62.1
    - 44.0
    - 68.6
    - 49.3
    - 38.8
    - 40.1
    - 50.6
    - 25.4
    - 53.0
    - 10.5
    - 13.8
  - - 18.9
    - 37.6
    - 36.4
    - 32.8
    - 14.3
    - 46.5
    - 0.0
    - 14.9
    - 31.4
    - 40.4
    - 27.2
    - 46.9
    - 49.7
    - 15.5
    - 47.1
    - 17.8
    - 49.8
    - 42.1
    - 45.7
    - 36.7
  - - 33.7
    - 28.9
    - 38.6
    - 36.8
    - 27.9
    - 60.3
    - 14.9
    - 0.0
    - 39.7
    - 36.4
    - 30.4
    - 41.6
    - 52.7
    - 23.8
    - 52.7
    - 17.0
    - 59.6
    - 42.5
    - 58.1
    - 51.4
  - - 27.7
    - 39.4
    - 16.1
    - 11.3
    - 20.8
    - 31.0
    - 31.4
    - 39.7
    - 0.0
    - 31.1
    - 13.8
    - 37.6
    - 22.8
    - 16.4
    - 16.8
    - 24.6
    - 20.0
    - 22.6
    - 23.5
    - 31.9
  - - 50.2
    - 13.4
    - 15.9
    - 19.9
    - 40.8
    - 62.1
    - 40.4
    - 36.4
    - 31.1
    - 0.0
    - 18.9
    - 7.0
    - 24.6
    - 30.1
    - 30.7
    - 22.6
    - 46.3
    - 12.8
    - 54.3
    - 61.1
  - - 32.2
    - 25.6
    - 9.2
    - 6.4
    - 23.1
    - 44.0
    - 27.2
    - 30.4
    - 13.8
    - 18.9
    - 0.0
    - 25.8
    - 22.8
    - 13.0
    - 22.4
    - 13.5
    - 32.6
    - 15.2
    - 37.2
    - 42.2
  - - 57.2
    - 14.9
    - 21.8
    - 26.3
    - 47.8
    - 68.6
    - 46.9
    - 41.6
    - 37.6
    - 7.0
    - 25.8
    - 0.0
    - 27.5
    - 37.1
    - 35.0
    - 29.1
    - 51.5
    - 17.1
    - 60.4
    - 68.0
  - - 50.3
    - 37.7
    - 14.1
    - 16.8
    - 42.4
    - 49.3
    - 49.7
    - 52.7
    - 22.8
    - 24.6
    - 22.8
    - 27.5
    - 0.0
    - 34.5
    - 9.5
    - 35.7
    - 26.9
    - 12.0
    - 39.4
    - 53.7
  - - 20.1
    - 32.4
    - 22.0
    - 17.8
    - 10.7
    - 38.8
    - 15.5
    - 23.8
    - 16.4
    - 30.1
    - 13.0
    - 37.1
    - 34.5
    - 0.0
    - 31.6
    - 12.0
    - 35.8
    - 28.3
    - 34.9
    - 33.3
  - - 44.3
    - 42.9
    - 16.2
    - 16.1
    - 37.5
    - 40.1
    - 47.1
    - 52.7
    - 16.8
    - 30.7
    - 22.4
    - 35.0
    - 9.5
    - 31.6
    - 0.0
    - 35.9
    - 17.4
    - 18.1
    - 30.0
    - 45.5
  - - 30.5
    - 21.3
    - 21.6
    - 19.9
    - 21.5
    - 50.6
    - 17.8
    - 17.0
    - 24.6
    - 22.6
    - 13.5
    - 29.1
    - 35.7
    - 12.0
    - 35.9
    - 0.0
    - 44.6
    - 26.0
    - 46.0
    - 45.2
  - - 40.2
    - 57.1
    - 30.5
    - 27.7
    - 36.8
    - 25.4
    - 49.8
    - 59.6
    - 20.0
    - 46.3
    - 32.6
    - 51.5
    - 26.9
    - 35.8
    - 17.4
    - 44.6
    - 0.0
    - 34.5
    - 14.9
    - 34.6
  - - 46.9
    - 25.7
    - 6.8
    - 11.9
    - 38.0
    - 53.0
    - 42.1
    - 42.5
    - 22.6
    - 12.8
    - 15.2
    - 17.1
    - 12.0
    - 28.3
    - 18.1
    - 26.0
    - 34.5
    - 0.0
    - 44.2
    - 54.4
  - - 31.4
    - 62.8
    - 38.6
    - 34.4
    - 31.4
    - 10.5
    - 45.7
    - 58.1
    - 23.5
    - 54.3
    - 37.2
    - 60.4
    - 39.4
    - 34.9
    - 30.0
    - 46.0
    - 14.9
    - 44.2
    - 0.0
    - 20.9
  - - 18.0
    - 65.7
    - 47.7
    - 42.6
    - 24.2
    - 13.8
    - 36.7
    - 51.4
    - 31.9
    - 61.1
    - 42.2
    - 68.0
    - 53.7
    - 33.3
    - 45.5
    - 45.2
    - 34.6
    - 54.4
    - 20.9
    - 0.0
  station_ids:
  - S1
  - S2
  - S3
  - S4
  - S5
  - S6
  - S7
  - S8
  - S9
  - S10
  - S11
  - S12
  - S13
  - S14
  - S15
  - S16
  - S17
  - S18
  - S19
  - S20
  station_names:
  - Station_1
  - Station_2
  - Station_3
  - Station_4
  - Station_5
  - Station_6
  - Station_7
  - Station_8
  - Station_9
  - Station_10
  - Station_11
  - Station_12
  - Station_13
  - Station_14
  - Station_15
  - Station_16
  - Station_17
  - Station_18
  - Station_19
  - Station_20
  lat:
  - 38.6722673
  - 38.7557728
  - 38.7601326
  - 38.7499502
  - 38.6903238
  - 38.6942703
  - 38.6810383
  - 38.6912724
  - 38.7342598
  - 38.7708651
  - 38.7400792
  - 38.7841972
  - 38.7852479
  - 38.7108659
  - 38.7708498
  - 38.7204542
  - 38.7493838
  - 38.7743543
  - 38.7167314
  - 38.6719082
  lon:
  - -9.1566153
  - -9.0528728
  - -9.1303345
  - -9.1373372
  - -9.1428402
  - -9.2362341
  - -9.1033813
  - -9.0625873
  - -9.162952
  - -9.0864659
  - -9.1238909
  - -9.0755619
  - -9.1549185
  - -9.1265225
  - -9.1751116
  - -9.0942301
  - -9.2172189
  - -9.1231339
  - -9.2267988
  - -9.208566
demand:
  base_lambda_per_dt: 0.35
energy:
  chargers_per_station:
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  - 12
  charge_rate_soc_per_hour:
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  - 0.35
  battery_kwh_per_vehicle: 0.5
  energy_cost_per_kwh_eur: 0.2
score:
  objective: client_satisfaction_normalized
  weights:
    w_unavail: 5.0
    w_reloc: 1.0
    w_charge: 1.0
    w_queue: 4.0
  scales:
    U0_unavailability: 0.25
    R0_reloc_km: 1.0
    C0_charge_cost_eur: 0.01
    Q0_queue_total: 10.0
  eps: 1.0e-06
seed: 44
meta:
  city: Lisbon, Portugal (synthetic)
  generator: synthetic_min_spacing
  center_lat: 38.7223
  center_lon: -9.1393
  radius_km: 9.0
  min_spacing_m: 700.0
  speed_kmh_for_travel_time: 15.0
